use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006009
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Rafael
Kitover
rkitover
Karen
Etheridge
ether
Jesse
Luehrs
doy
Michael
Schwern
schwern
lib
MooseX
AlwaysCoerce
